### ISSUE TITLE
这个是为什么：Cannot read properties of undefined (reading 'rks')

### ISSUE THREAD

**Issue by vcfch843875** [Catrong/phi-plugin#158]
phi插件和TRSS-Yunzai均为最新版，依赖包也是最新版

```
[16:46:43.668][INFO][1207421255] recv from: [Private: 843875618(friend)] #phi score Spasmodic
[16:46:43.681][INFO][無限蘿莉製max⁧⁧ ~喵⁦(843875618)][#phi score Spasmodic][phi-b19(singlescore)][开 开始处理]
[16:46:43.720][ERRO][無限蘿莉製max⁧⁧ ~喵⁦(843875618)][#phi score Spasmodic][phi-b19(singlescore)] Ty  ypeError: Cannot read properties of undefined (reading 'rks')
    at phib19.singlescore (file:///C:/msys64/home/vcfch/TRSS_AllBot/TRSS-Yunzai/plugins/phi-plugin/apps/b19.js:562:78)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async PluginsLoader.deal (file:///C:/msys64/home/vcfch/TRSS_AllBot/TRSS-Yunzai/lib/plugins/loader.js:262:41) {
  [stack]: [Getter/Setter: "TypeError: Cannot read properties of undefined (reading 'rks')\n" +
    '    at phib19.singlescore (file:///C:/msys64/home/vcfch/TRSS_AllBot/TRSS-Yunzai/plugins/phi-plugin/apps/b19.js:562:78)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
    '    at async PluginsLoader.deal (file:///C:/msys64/home/vcfch/TRSS_AllBot/TRSS-Yunzai/lib/plugins/loader.js:262:41)'],
  [message]: "Cannot read properties of undefined (reading 'rks')"
}
```

**Comment by Catrong** [comment]
可能修复了，可以更新后重试，如果依旧有问题可以反馈一下出现问题的sessionToken

**Comment by vcfch843875** [comment]
现在没有问题了，我先关闭吧。感谢！ @Catrong
