### ISSUE TITLE
#rks报错

### ISSUE THREAD

**Issue by lhr8192** [Catrong/phi-plugin#6]
#rksacc输入CROSS†SOUL时报错
```
[MiaoYz][22:15:31.314][ERRO] [phigrosrks计算器][inputing]
[MiaoYz][22:15:31.315][ERRO] TypeError: Cannot read properties of undefined (reading 'at_level')
    at ask (file:///E:/Miao-Yunzai/plugins/phi-plugin/apps/phirks.js:244:31)
    at phirks.inputing (file:///E:/Miao-Yunzai/plugins/phi-plugin/apps/phirks.js:216:13)
    at PluginsLoader.deal (file:///E:/Miao-Yunzai/lib/plugins/loader.js:251:57)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by Catrong** [comment]
应该已经修复了，如果还有问题的话可以继续在这里反馈，谢谢
