### ISSUE TITLE
载入re8模块错误

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Catrong/phi-plugin#93]
```JavaScript
1|Miao-Yun | [MiaoYz][00:38:52.506][INFO] [Phi-Plugin][re8] 导入 unix? 模块
1|Miao-Yun | [MiaoYz][00:38:52.683][ERRO] [phi-plugin]载入插件错误：re8
1|Miao-Yun | [MiaoYz][00:38:52.684][ERRO] Error: libnode.so.72: cannot open shared object file: No such file or directory
1|Miao-Yun |     at Module._extensions..node (node:internal/modules/cjs/loader:1340:18)
1|Miao-Yun |     at Module.load (node:internal/modules/cjs/loader:1119:32)
1|Miao-Yun |     at Module._load (node:internal/modules/cjs/loader:960:12)
1|Miao-Yun |     at Module.require (node:internal/modules/cjs/loader:1143:19)
1|Miao-Yun |     at Hook._require.Module.require (/home/yuyue/Yunzai-Bot/node_modules/.pnpm/require-in-the-middle@5.2.0/node_modules/require-in-the-middle/index.js:101:39)
1|Miao-Yun |     at require (node:internal/modules/cjs/helpers:121:18)
1|Miao-Yun |     at file:///home/yuyue/Miao-Yunzai/plugins/phi-plugin/apps/re8.js:26:28 {
1|Miao-Yun |   code: 'ERR_DLOPEN_FAILED'
1|Miao-Yun | }
```

**Comment by YuYue-Amatsuki** [comment]
NodeJS版本：18.17.1

**Comment by Catrong** [comment]
如果是arch的话暂时不支持arch系统哦，如果不是请说一下是什么系统（）

**Comment by YuYue-Amatsuki** [comment]
> 如果是arch的话暂时不支持arch系统哦，如果不是请说一下是什么系统（）

Ubuntu 22.04 LTS

**Comment by Catrong** [comment]
收到，谢谢

**Comment by Catrong** [comment]
貌似修复了，更新一下试试（）

**Comment by Catrong** [comment]
手动安装一下libzip4试试（

**Comment by YuYue-Amatsuki** [comment]
> 手动安装一下libzip4试试（

Ubuntu自带libzip4![Screenshot_2023-10-18-12-59-33-81_3d419158bad5872c40592a6c9956e692.jpg](https://github.com/Catrong/phi-plugin/assets/86163024/d815eb42-88cf-4829-b9a9-d445528717c6)

**Comment by Catrong** [comment]
唔，初步判断是.node和系统的nodejs的版本不同（）正在找解决方法（）感谢理解

**Comment by Catrong** [comment]
已修复，更新一下试试
